# Generated by Django 5.2.7 on 2026-02-13 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("call_type", models.CharField(choices=[("audio", "Audio"), ("video", "Video")], default="audio", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("ended", "Ended"),
                            ("missed", "Missed"),
                            ("failed", "Failed"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_sessions", to="chat.chat"),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ended_call_sessions",
                        to="chat.profile",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_call_sessions",
                        to="chat.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="chat.callsession"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_participations", to="chat.profile")),
            ],
            options={
                "unique_together": {("call", "user")},
            },
        ),
    ]
