# Generated by Django 6.0.2 on 2026-02-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge'),
        ('chat', '0009_profile_call_status'),
    ]

    operations = [
    ]
