# Generated by Django 5.2.17 on 2026-09-20 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_adult_flag_and_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('message', 'Сообщение'), ('chat', 'Чат или канал'), ('sound_pack', 'Пак звуков'), ('sticker_pack', 'Пак стикеров'), ('theme', 'Тема оформления')], max_length=16),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('data', models.JSONField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='chat.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_by', to='chat.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_themes', to='chat.profile')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('user', 'theme')},
            },
        ),
    ]
