# Generated by Django 5.2.17 on 2026-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
