# Generated by Django 5.2.17 on 2026-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_chat_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundpack',
            name='cover_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
