# Generated by Django 5.2.17 on 2026-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_soundpack_cover'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='msg_chat_created_idx'),
        ),
    ]
