version = 5.1.0
archive_dir = /etc/letsencrypt/archive/sux.cardiokit.beget.tech
cert = /etc/letsencrypt/live/sux.cardiokit.beget.tech/cert.pem
privkey = /etc/letsencrypt/live/sux.cardiokit.beget.tech/privkey.pem
chain = /etc/letsencrypt/live/sux.cardiokit.beget.tech/chain.pem
fullchain = /etc/letsencrypt/live/sux.cardiokit.beget.tech/fullchain.pem
[renewalparams]
account = 62e2f2b0073abb23613ad1065e1d5ef9
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
sux.cardiokit.beget.tech = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2025-11-04T03:39:59
