server {
    listen 80;
    server_name _;

    # Статические файлы
    location /static/ {
        alias /app/static/;
    }

    # Основное проксирование к Django
    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $http_host;  # ← Исправьте на $http_host
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}